-- Create beta_signups table
create table if not exists beta_signups (
  id bigint primary key generated by default as identity,
  email text not null unique,
  platform text not null check (platform in ('ios', 'android')),
  goal text check (goal in ('general', 'event')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  status text default 'pending' check (status in ('pending', 'invited', 'joined'))
);

-- Create index on email for faster lookups
create index if not exists idx_beta_signups_email on beta_signups(email);
create index if not exists idx_beta_signups_platform on beta_signups(platform);
create index if not exists idx_beta_signups_created_at on beta_signups(created_at);

-- Enable RLS
alter table beta_signups enable row level security;

-- Allow inserts from public (for signups)
create policy "Allow public inserts" on beta_signups
  for insert with check (true);

-- Allow reads only from authenticated users (for CRM)
create policy "Allow authenticated reads" on beta_signups
  for select using (auth.role() = 'authenticated');
