-- Create user_setups table for equipment and workout photos
create table if not exists user_setups (
  id bigint primary key generated by default as identity,
  email text not null,
  equipment text,
  file_count integer,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create index on email for faster lookups
create index if not exists idx_user_setups_email on user_setups(email);
create index if not exists idx_user_setups_created_at on user_setups(created_at);

-- Enable RLS
alter table user_setups enable row level security;

-- Allow inserts from public (for setup submissions)
create policy "Allow public inserts" on user_setups
  for insert with check (true);

-- Allow reads only from authenticated users (for CRM)
create policy "Allow authenticated reads" on user_setups
  for select using (auth.role() = 'authenticated');
