-- Create trainer_signups table
create table if not exists trainer_signups (
  id bigint primary key generated by default as identity,
  name text not null,
  email text not null unique,
  phone text not null,
  gym_name text,
  client_count text,
  experience_years integer,
  interest_areas text[] default '{}',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  status text default 'pending' check (status in ('pending', 'reviewed', 'approved', 'rejected'))
);

-- Create indexes
create index if not exists idx_trainer_signups_email on trainer_signups(email);
create index if not exists idx_trainer_signups_status on trainer_signups(status);
create index if not exists idx_trainer_signups_created_at on trainer_signups(created_at);

-- Enable RLS
alter table trainer_signups enable row level security;

-- Allow inserts from public (for signups)
create policy "Allow public inserts" on trainer_signups
  for insert with check (true);

-- Allow reads only from authenticated users (for CRM)
create policy "Allow authenticated reads" on trainer_signups
  for select using (auth.role() = 'authenticated');
